# 文件位置: docker-compose.yml

# 先定義 volumes
volumes:
  python-packages:    # 後端 Python 依賴
  node_modules:       # 前端 Node.js 依賴
  resume_store:      # RAG 向量存儲

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/models:/app/models:ro                 # 模型目錄，唯讀
      - resume_store:/app/models/resume_store           # 使用 named volume
      - python-packages:/usr/local/lib/python3.9/site-packages
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MODEL_PATH=/app/models/Llama3-ChatQA-1.5-8B.gguf
      - RESUME_PATH=/app/resumes/EN_CV2.txt
      - MODEL_VERSION=llama3
      - LOG_LEVEL=INFO
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
